name: Build demux container (env/demux.Dockerfile)

on:
  push:
    paths:
    - 'env/demux.Dockerfile'
    - '.github/workflows/build_demux_docker.yml'
  pull_request:
    paths:
    - 'env/demux.Dockerfile'
    - '.github/workflows/build_demux_docker.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Build Tools
    - name: Build and Publish
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        name: sjwidmay/stitch_nf
        username: ${{ secrets.SJW_DOCKER_USER }}
        password: ${{ secrets.SJW_DOCKER_PASS }}
        snapshot: true
        dockerfile: demux.Dockerfile
        workdir: "env"
        tags: "demux"