name: Build Rmarkdown container (env/StatMarkdown.Dockerfile)

on:
  push:
    paths:
    - 'env/StatMarkdown.Dockerfile'
    - 'env/stat_markdown.yml'
    - '.github/workflows/build_StatMarkdown.yml'
  pull_request:
    paths:
    - 'env/StatMarkdown.Dockerfile'
    - 'env/stat_markdown.yml'
    - '.github/workflows/build_StatMarkdown.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Build Tools
    - name: Build and Publish
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        name: sjwidmay/stitch_nf
        username: ${{ secrets.SJW_DOCKER_USER }}
        password: ${{ secrets.SJW_DOCKER_PASS }}
        snapshot: true
        dockerfile: StatMarkdown.Dockerfile
        workdir: "env"
        tags: "stats_markdown"