name: Build bbtools container (env/bbtools.Dockerfile)

on:
  push:
    paths:
    - 'env/bbtools.Dockerfile'
    - '.github/workflows/build_bbtools_docker.yml'
  pull_request:
    paths:
    - 'env/bbtools.Dockerfile'
    - '.github/workflows/build_bbtools_docker.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Build Tools
    - name: Build and Publish
      uses: elgohr/Publish-Docker-Github-Action@v4
      with:
        name: sjwidmay/stitch_nf
        username: ${{ secrets.SJW_DOCKER_USER }}
        password: ${{ secrets.SJW_DOCKER_PASS }}
        snapshot: true
        dockerfile: bbtools.Dockerfile
        workdir: "env"
        tags: "bbtools"